// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfQGymlUC2CnsxdB8YCl3_XlDJoGcTICk',
    appId: '1:846047241826:web:d4abc7f06c6ffb47f8133b',
    messagingSenderId: '846047241826',
    projectId: 'schoolsync-b185a',
    authDomain: 'schoolsync-b185a.firebaseapp.com',
    storageBucket: 'schoolsync-b185a.firebasestorage.app',
    measurementId: 'G-FQN5LXMD2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfckp0p14hzRZH_r_DXKBxq-pjwSEzMk4',
    appId: '1:846047241826:android:e4bd56c935b028a5f8133b',
    messagingSenderId: '846047241826',
    projectId: 'schoolsync-b185a',
    storageBucket: 'schoolsync-b185a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Uf2mizKNvzSD2xb8BEGZDqUgMqZ8psI',
    appId: '1:846047241826:ios:c43019377d764ab4f8133b',
    messagingSenderId: '846047241826',
    projectId: 'schoolsync-b185a',
    storageBucket: 'schoolsync-b185a.firebasestorage.app',
    iosBundleId: 'com.example.appv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Uf2mizKNvzSD2xb8BEGZDqUgMqZ8psI',
    appId: '1:846047241826:ios:c43019377d764ab4f8133b',
    messagingSenderId: '846047241826',
    projectId: 'schoolsync-b185a',
    storageBucket: 'schoolsync-b185a.firebasestorage.app',
    iosBundleId: 'com.example.appv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfQGymlUC2CnsxdB8YCl3_XlDJoGcTICk',
    appId: '1:846047241826:web:be94a71a2e387f0af8133b',
    messagingSenderId: '846047241826',
    projectId: 'schoolsync-b185a',
    authDomain: 'schoolsync-b185a.firebaseapp.com',
    storageBucket: 'schoolsync-b185a.firebasestorage.app',
    measurementId: 'G-SB80189EJB',
  );
}
